# Generated by Django 4.0.3 on 2022-05-02 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repaid_at', models.DateTimeField(null=True)),
                ('reason', models.TextField(max_length=500)),
                ('debtee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtee_transactions', to=settings.AUTH_USER_MODEL)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
